#!/bin/sh
curl -L https://github.com/curl/curl/releases/download/curl-8_15_0/curl-8.15.0.tar.gz -o curl.tar.gz
tar -xvf curl.tar.gz
cd curl-8.15.0
./configure --with-openssl
make -j$(nproc)
make install
