#!/bin/sh
if [ $# -eq 0 ]; then
    echo "  teto -S <package>    install package"
    echo "  teto -R <package>    remove package"
    echo "  teto -U              upgrade packages"
    exit 0
fi
case "$1" in
    -S)
        shift
        sh /teto/modules/install "$@"
        ;;
    -R)
        shift
        sh /teto/modules/remove "$@"
        ;;
    -U)
        shift
        sh /teto/modules/upgrade "$@"
        ;;
    *)
        echo "unkown command"
        ;;
esac
