#!/bin/sh
curl -L https://ftp.fau.de/gnu/mpc/mpc-1.3.1.tar.gz -o mpc.tar.gz
tar -xf mpc.tar.gz
cd mpc-1.3.1
./configure --prefix=/usr/local --with-gmp=/usr/local --with-mpfr=/usr/local
make -j$(nproc)
make install
