#!/bin/sh
set -e
. ./config
sh /teto/modules/install $depends
curl -L $url -o $file
tar -xf $file
for d in $dir; do
    if [ -d "$d" ]; then
        cd "$d"
        break
    fi
done
./$configure
sh /teto/modules/build/$build
